name: daily empty commit

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 8 * * *"
    - cron: "0 16 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: configure git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: create an empty commit
        run: |
          git commit --allow-empty -m "daily empty commit"
          git push origin main
